### ISSUE TITLE
AttributeError: 'MAVLink' object has no attribute 'play_tune_send'

### ISSUE THREAD

**Issue by CodingGhost** [ArduPilot/pymavlink#674]
When executing the play_tune_send command, sometimes(its really random to me and not always reproducable) I get 
AttributeError: 'MAVLink' object has no attribute 'play_tune_send'

what could that be? its really strange as it only happens sometimes, even when testing with the exact same code.

**Comment by CodingGhost** [comment]
this is really bad. I cannot use it like that, any ideas?

**Comment by peterbarker** [comment]
@CodingGhost this is almost certainly because you're not using the correct bindings; make sure `MAVLINK20` is in your environment to use the mavlink2 bindings.

I can't think there's any race condition in the pymavlink bindings themselves which would lead to the random reproducibility - are you running threads in your application?  If so - look there for issues, sorry :-)

**Comment by CodingGhost** [comment]
I also thought about that, but I have os.environ["MAVLINK20"]='1' at the top of my program.
Also, if it only were that, how come it only happens sometimes? shouldnt it like not work at all?

**Comment by CodingGhost** [comment]
changing master.target_system,master.target_component to 1,0 solved this, propably because sometimes the message was sent to the herelink instead of the cube.
